version: '3.3'

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8087"
    ports:
      - "9085:80"
      - "9086:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - greenbeauty_network
    deploy:
      mode: replicated
      replicas: 1

  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - greenbeauty_network

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8087:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.greenbeautycenter_wordpress.rule=Host(`www.greenbeautycenter.fr`)"
        - "traefik.http.services.greenbeautycenter_wordpress.loadbalancer.server.port=80"
    networks:
      - greenbeauty_network

volumes:
  db_data:
  wp_data:

networks:
  greenbeauty_network:
    external: true
