version: '3.8'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.website1_resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.website1_resolver.acme.email=kouahofrancis@gmail.com"
      - "--certificatesresolvers.website1_resolver.acme.storage=/letsencrypt/wordpress.json"
      - "--certificatesresolvers.website2_resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.website2_resolver.acme.email=kouahofrancis@gmail.com"
      - "--certificatesresolvers.website2_resolver.acme.storage=/letsencrypt/wordpress.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/traefik/letsencrypt:/letsencrypt"
    networks:
      - traefik_network

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: website1WP
    volumes:
      - "./data/website1:/var/www/html"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.rule=Host(`greenbeautycenter.fr`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=wordpress_resolver"

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - traefik_network
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql

networks:
  traefik_network:
    external: true
